import type { Metadata } from "next";
import { Fraunces } from "next/font/google";
import Script from 'next/script';
import "./globals.css";
import "./responsive.css";
import Header from "@/components/header";
import PathnameHandler from "@/components/pathname-handler";
import { ConsentManager } from "./consent-manager";

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Khim Asian Restaurant",
  description: "Generated by Khim Asian Restaurant",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.1.0/dist/cookieconsent.css"/>
      </head>
      <body
        className={`${fraunces.variable} antialiased`}
      >
        <ConsentManager>

          <PathnameHandler />
          <Header />
          {children}

        </ConsentManager>
      </body>
    </html>
  )
}
