import type { Metadata } from "next";
import { Fraunces } from "next/font/google";
import "./globals.css";
import "./responsive.css";
import Header from "@/components/header";
import PathnameHandler from "@/components/pathname-handler";

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (window.location.pathname === '/menu' || window.location.pathname === '/contact') {
                document.documentElement.classList.add('inner--page');
              }
            `,
          }}
        />
      </head>
      <body
        className={`${fraunces.variable} antialiased`}
      >
        <PathnameHandler />
        <Header />
        {children}
      </body>
    </html>
  );
}
